model_list:
  - model_name: gemini-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemma
    litellm_params:
      model: gemini/gemma-4-31b-it
      api_key: os.environ/GEMINI_API_KEY
  - model_name: kimi
    litellm_params:
      model: openrouter/moonshotai/kimi-k2
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: qwen3-ollama-chat
    litellm_params:
      model: ollama_chat/qwen3:4b
  - model_name: qwen3-ollama-compat
    litellm_params:
      model: ollama/qwen3:4b
  - model_name: gemini3
    litellm_params:
      model: gemini/gemini-3-flash-preview
      api_key: os.environ/GEMINI_API_KEY
